### ISSUE TITLE
How to support multiple websocket clients?

### ISSUE THREAD

**Issue by elieobeid7** [gd-com/examples#2]
The example of websocket only support 1 client, if you try to connect two, you get an error, what changes should one make to the examples in order to support multiple clients (up to 8)? 
I want to send data from a client to the next.

**Comment by Tilican** [comment]
Hey,
I'm going to make a tchat example with websocket on godot 3.1.1

**Comment by elieobeid7** [comment]
It turns out that it's a bug by Godot, opened an issue there, closing this one
