### ISSUE TITLE
Does it work on ios and Android apps?

### ISSUE THREAD

**Issue by elieobeid7** [gd-com/examples#3]
Does websockets work on ios and Android apps? And also a quick question because the examples are confusing me

If i have a websockets server. Say feathers js and I have a /users endpoint, how to read ans write to it?

Finally does it work with sockets io or uwebsocketsjs?

**Comment by Tilican** [comment]
Hi,
This library is for **server side**, ios / android is the "front" with godot.

In your Godot project, you have to send packet to your own server ( here in nodejs ), and with this library you can serialize/unserialize data.

In examples, i try websocket using [npm ws](https://www.npmjs.com/package/ws) and [npm express-ws](https://www.npmjs.com/package/express-ws). 

`If i have a websockets server. Say feathers js and I have a /users endpoint, how to read ans write to it?
`
This lib is for server side, if you want to write on it with godot, go to see [godot doc](https://docs.godotengine.org/en/3.1/).


`Finally does it work with sockets io or uwebsocketsjs?`
I do not advise you to use an extra with many feature WS library like socket-io, make it simple !

**Comment by elieobeid7** [comment]
This library works great and worked with uwebsockets.js, indeed it's just a serialization library, the examples make it seem like it's something complicated, I ended up using putvar and getvar only. Thank you.
