### ISSUE TITLE
SSL Examples

### ISSUE THREAD

**Issue by dev-clavis** [gd-com/examples#8]
Hi thank you
these are some Awesome examples.

Could you add some SSL or encrypted Examples as well? (TCP with SSL, and WSS)

**Comment by tilican** [comment]
Hey @dev-clavis :)
I never tried to use SSL, sorry.
I'll try to see what I can do, if you find a solution don't hesitate to make a PR
Thanks

**Comment by tilican** [comment]
Hey @dev-clavis i add basic example on websocket and TCP if you want to check :)
